apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepositories
  - projects/fusion/dev/instance_a/flux-kustomization.yaml
  - projects/fusion/dev/instance_b/flux-kustomization.yaml
