apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fusion-content-main
  namespace: flux-system
spec:
  interval: 1m
  url: http://gitea.fusion.local/gitea_admin/fusion-content.git
  ref:
    branch: main
