apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fusion-monitoring-shared
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./dev-cluster/projects/monitoring/dev/shared
  prune: true
  wait: true
  targetNamespace: monitoring
