apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-grafana
  namespace: monitoring
spec:
  interval: 1m
  releaseName: fusion-grafana
  install:
    createNamespace: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  chart:
    spec:
      chart: ./deployment
      sourceRef:
        kind: GitRepository
        name: fusion-grafana-main
        namespace: flux-system
      valuesFiles:
        - deployment/values.yaml
