apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-spectra
  namespace: fusion-dev-b
spec:
  values:
    ingress:
      enabled: true
      host: spectra-b.fusion.local
      tls:
        enabled: false
    config:
      bffUrl: http://bff-b.fusion.local
