apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-index
  namespace: fusion-dev-b
spec:
  interval: 1m
  releaseName: fusion-index
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./deployment
      sourceRef:
        kind: GitRepository
        name: fusion-index-main
        namespace: flux-system
      valuesFiles:
        - deployment/values.yaml
        - deployment/values-dev.yaml
