apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-bff-postgres
  namespace: fusion-dev-a
spec:
  interval: 1m
  releaseName: fusion-bff-postgres
  install:
    createNamespace: true
  chart:
    spec:
      chart: postgresql
      version: "~16.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: fusion_bff
      password: devpass
      database: fusion_bff
    primary:
      persistence:
        enabled: false
