apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-content
  namespace: fusion-dev-a
spec:
  interval: 1m
  releaseName: fusion-content
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./deployment
      sourceRef:
        kind: GitRepository
        name: fusion-content-main
        namespace: flux-system
      valuesFiles:
        - deployment/values.yaml
        - deployment/values-local.yaml
