apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-bff
  namespace: fusion-dev-a
spec:
  interval: 1m
  releaseName: fusion-bff
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./deployment
      sourceRef:
        kind: GitRepository
        name: fusion-bff-main
        namespace: flux-system
      valuesFiles:
        - deployment/values.yaml
