apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fusion-forge
  namespace: fusion-dev-a
spec:
  values:
    server:
      config:
        indexBackendURL: "http://fusion-index-backend.fusion-dev-a.svc.cluster.local:8080"
    watcher:
      config:
        indexBackendURL: "http://fusion-index-backend.fusion-dev-a.svc.cluster.local:8080"
